-- Admin-managed branding media: images for the public landing slideshow
-- (LANDING) and the auth-page background (AUTH). Bytes live on disk under
-- uploads/branding/; this table tracks metadata and ordering.
CREATE TABLE branding_images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name    VARCHAR(255)  NOT NULL,
    content_type VARCHAR(128)  NOT NULL,
    size_bytes   BIGINT        NOT NULL,
    storage_key  VARCHAR(512)  NOT NULL,
    slide_kind   VARCHAR(16)   NOT NULL, -- LANDING | AUTH
    caption      VARCHAR(255),
    sort_order   INT           NOT NULL DEFAULT 0,
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP     NOT NULL
);

CREATE INDEX idx_branding_active_kind
    ON branding_images (active, slide_kind, sort_order);
