-- RWB Project Review System — initial schema (SRS v2.1)

CREATE TABLE organizations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    password_hash           VARCHAR(255) NOT NULL,
    full_name               VARCHAR(255) NOT NULL,
    role                    VARCHAR(32)  NOT NULL DEFAULT 'MANAGER',
    account_status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION',
    organization_id         BIGINT REFERENCES organizations (id),
    email_verification_token VARCHAR(64),
    email_verified_at       TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'MANAGER', 'REVIEWER')),
    CONSTRAINT chk_users_status CHECK (account_status IN (
        'PENDING_EMAIL_VERIFICATION',
        'PENDING_ADMIN_REVIEW',
        'ACTIVE_FIRST_PROJECT_REQUIRED',
        'ACTIVE',
        'REJECTED'
    ))
);

CREATE INDEX idx_users_status ON users (account_status);

CREATE TABLE projects (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    docket_number VARCHAR(32) NOT NULL UNIQUE,
    title        VARCHAR(255) NOT NULL,
    summary      TEXT,
    category     VARCHAR(64),
    status       VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    owner_id     BIGINT NOT NULL REFERENCES users (id),
    reviewer_id  BIGINT REFERENCES users (id),
    submitted_at TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chk_projects_status CHECK (status IN (
        'DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'RESUBMITTED', 'ARCHIVED'
    ))
);

CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_owner ON projects (owner_id);
CREATE INDEX idx_projects_created ON projects (created_at DESC);

CREATE TABLE attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(128),
    size_bytes   BIGINT NOT NULL DEFAULT 0,
    storage_key  VARCHAR(512),
    version      INTEGER NOT NULL DEFAULT 1,
    project_id   BIGINT NOT NULL REFERENCES projects (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_attachments_project ON attachments (project_id);

CREATE TABLE reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision   VARCHAR(32) NOT NULL,
    comments   TEXT,
    project_id BIGINT NOT NULL REFERENCES projects (id),
    reviewer_id BIGINT NOT NULL REFERENCES users (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chk_reviews_decision CHECK (decision IN ('APPROVED', 'REJECTED', 'NOTES'))
);

CREATE INDEX idx_reviews_project ON reviews (project_id);

CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject      VARCHAR(255) NOT NULL,
    body         TEXT,
    is_read      BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_id BIGINT NOT NULL REFERENCES users (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_recipient ON notifications (recipient_id);

CREATE TABLE audit_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(255),
    action     VARCHAR(64) NOT NULL,
    detail     TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_created ON audit_logs (created_at DESC);
