-- Formal correspondence between any two active accounts (external companies,
-- reviewers, division managers, super reviewers, administrators).

CREATE TABLE messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    BIGINT NOT NULL REFERENCES users (id),
    recipient_id BIGINT NOT NULL REFERENCES users (id),
    subject      VARCHAR(255),
    body         TEXT NOT NULL,
    is_read      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_messages_recipient ON messages (recipient_id);
CREATE INDEX idx_messages_sender ON messages (sender_id);
